/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/contactDetails`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/floors/level0`; params?: Router.UnknownInputParams; } | { pathname: `/floors/level1`; params?: Router.UnknownInputParams; } | { pathname: `/floors/level2`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/mappage`; params?: Router.UnknownInputParams; } | { pathname: `/mappage/pathGraph`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/DrSchedule`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/map`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/database`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/doctor/contactDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/doctor/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/floors/level0`; params?: Router.UnknownOutputParams; } | { pathname: `/floors/level1`; params?: Router.UnknownOutputParams; } | { pathname: `/floors/level2`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/mappage`; params?: Router.UnknownOutputParams; } | { pathname: `/mappage/pathGraph`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/DrSchedule`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/map`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/database${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/doctor/contactDetails${`?${string}` | `#${string}` | ''}` | `/doctor/schedule${`?${string}` | `#${string}` | ''}` | `/floors/level0${`?${string}` | `#${string}` | ''}` | `/floors/level1${`?${string}` | `#${string}` | ''}` | `/floors/level2${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/mappage${`?${string}` | `#${string}` | ''}` | `/mappage/pathGraph${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/tabs/alerts${`?${string}` | `#${string}` | ''}` | `/tabs/DrSchedule${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs/map${`?${string}` | `#${string}` | ''}` | `/tabs/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/contactDetails`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/floors/level0`; params?: Router.UnknownInputParams; } | { pathname: `/floors/level1`; params?: Router.UnknownInputParams; } | { pathname: `/floors/level2`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/mappage`; params?: Router.UnknownInputParams; } | { pathname: `/mappage/pathGraph`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/DrSchedule`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/map`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
